# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sche_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2199, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
