# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userinfo_sql_review_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sql_review_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sql.sqlreview_role'),
        ),
    ]
