# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171126_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='sql_review_role',
        ),
    ]
